name: Reusable on push feature

on:
    workflow_call:

jobs:
    feature-branch-push:
        name: Feature Push
        runs-on: ubuntu-24.04
        steps:
            - name: Get artifact version
              id: version
              uses: keeonline/gh-actions/actions/artifact-version@v0.0.8

            - name: Output values
              run: |
                echo "value=${{steps.version.outputs.value}}"
                echo "projected_release=${{steps.version.outputs.projected_release}}"