name: On Push to Feature

on:
    push:
        branches:
            - '**'
            - '!main'

jobs:
    on-push-feature:
        name: Push to feature branch
        uses: ./.github/workflows/on-push-feature.yml